# RT-Thread building script for component

Import('RTT_ROOT')
from building import *

objs = []

if GetDepend('USE_MA35_AARCH32'):
    cwd     = GetCurrentDir()
    src = Glob('*.c') + Glob('*.cpp')
    CPPPATH = [cwd]

    group = DefineGroup('vc8000', src, depend = [''], CPPPATH = CPPPATH)

    list = os.listdir(cwd)
    for d in list:
        path = os.path.join(cwd, d)
        if os.path.isfile(os.path.join(path, 'SConscript')):
            objs = objs + SConscript(os.path.join(d, 'SConscript'))
    objs = objs + group

Return('objs')
